volumes:
  exchange_postgres:
  exchange_redis:
  exchange_static:
  exchange_rabbitmq:
  exchange_csv:
  exchange_logs_web:
  exchange_logs_default:
  exchange_logs_check_condition:
  exchange_logs_positions:
  exchange_logs_market:
  exchange_logs_websocket_okx_orders:
  exchange_logs_websocket_okx_positions:
  exchange_logs_websocket_okx_ask_bid:
  exchange_logs_websocket_okx_last_price:
  exchange_logs_websocket_okx_market_price:
  exchange_logs_websocket_binance_ask_bid:

networks:
  layer:
    driver: bridge

services:
  web:
    image: exchange:latest
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/wait-for-it.sh -q -s -h postgres -p 5432 -- /app/entrypoint.sh
    restart: always
    volumes:
      - exchange_static:/app/static
      - exchange_csv:/opt/csv
      - exchange_logs_web:/app/logs
    networks:
      - layer
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    logging:
      driver: 'none'

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - .env
    volumes:
      - exchange_rabbitmq:/var/lib/rabbitmq
    networks:
      - layer

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - exchange_static:/app/static:ro
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_nginx
        syslog-facility: local5

  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=2000'
    env_file:
      - .env
    volumes:
      - exchange_postgres:/var/lib/postgresql/data
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_postgres
        syslog-facility: local5

  redis:
    image: redis:latest
    entrypoint: redis-server --appendonly yes --maxmemory-policy volatile-ttl --aof-use-rdb-preamble yes --save "" --maxclients 65000
    volumes:
      - exchange_redis:/data
    networks:
      - layer

  # flower:
  #   image: exchange:latest
  #   entrypoint: /app/wait-for-it.sh -q -s -h rabbitmq -p 5672 -- celery -A exchange flower -l INFO --host=0.0.0.0 --port=5555
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "51455:5555"
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - layer

  beat:
    image: exchange:latest
    entrypoint: sh -c "sleep 5 && celery -A exchange beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - web
      - rabbitmq
      - redis
      - postgres
      - default
      - positions
      - market
      - check_condition
      - websocket_okx_orders
      - websocket_okx_ask_bid
      - websocket_okx_positions
      - websocket_binance_ask_bid
      - websocket_okx_last_price
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  default:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 5 -l INFO -Q default
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_default:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  check_condition:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 100 -l INFO -Q check_condition
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_check_condition:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  positions:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 30 -l INFO -Q positions
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_positions:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  market:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 30 -l INFO -Q market 
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_market:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  websocket_okx_orders:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_orders
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_websocket_okx_orders:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  websocket_okx_last_price:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_last_price
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_websocket_okx_last_price:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  websocket_okx_ask_bid:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_ask_bid
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_websocket_okx_ask_bid:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  websocket_binance_ask_bid:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_binance_ask_bid
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    volumes:
      - exchange_csv:/opt/csv
      - exchange_logs_websocket_binance_ask_bid:/app/logs
    networks:
      - layer
    logging:
      driver: 'none'

  websocket_okx_market_price:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_market_price
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_websocket_okx_market_price:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'

  websocket_okx_positions:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_positions
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - exchange_logs_websocket_okx_positions:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: 'none'
