volumes:
  exchange_postgres:
  exchange_redis:
  exchange_static:
  exchange_rabbitmq:
  exchange_ask_bid:

networks:
  layer:
    driver: bridge

services:
  web:
    image: exchange:latest
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/wait-for-it.sh -q -s -h postgres -p 5432 -- /app/entrypoint.sh
    restart: always
    volumes:
      - exchange_static:/app/static
    networks:
      - layer
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    logging:
      driver: syslog
      options:
        tag: exchange_web
        syslog-facility: local5

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - .env
    volumes:
      - exchange_rabbitmq:/var/lib/rabbitmq
    ports:
      - "38445:15672"
      - "38692:15692"
    networks:
      - layer

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - exchange_static:/app/static:ro
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - layer

  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=2000'
    env_file:
      - .env
    volumes:
      - exchange_postgres:/var/lib/postgresql/data
    networks:
      - layer

  redis:
    image: redis:latest
    entrypoint: redis-server --appendonly yes --maxmemory-policy volatile-ttl --aof-use-rdb-preamble yes --save "" --maxclients 65000
    volumes:
      - exchange_redis:/data
    networks:
      - layer

  flower:
    image: exchange:latest
    entrypoint: celery -A exchange flower -l INFO --host=0.0.0.0 --port=5555
    restart: always
    env_file:
      - .env
    ports:
      - "51455:5555"
    depends_on:
      - rabbitmq
    networks:
      - layer

  beat:
    image: exchange:latest
    entrypoint: sh -c "sleep 5 && celery -A exchange beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - web
      - rabbitmq
      - redis
      - postgres
      - default
      - positions
      - market
      - check_condition
      - websocket_okx_orders
      - websocket_okx_ask_bid
      - websocket_okx_positions
      - websocket_binance_ask_bid
      - websocket_okx_last_price
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_scheduler
        syslog-facility: local5

  default:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 5 -l INFO -Q default
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_default
        syslog-facility: local5

  check_condition:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 30 -l INFO -Q check_condition
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_check_condition
        syslog-facility: local5

  positions:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 10 -l INFO -Q positions
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_positions
        syslog-facility: local5

  market:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 10 -l INFO -Q market 
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_market
        syslog-facility: local5

  websocket_okx_orders:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_orders
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket_okx_orders
        syslog-facility: local5

  websocket_okx_last_price:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_last_price
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket_okx_last_price
        syslog-facility: local5

  websocket_okx_ask_bid:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_ask_bid
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    volumes:
      - exchange_ask_bid:/opt/ask_bid
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket_okx_ask_bid
        syslog-facility: local5

  websocket_binance_ask_bid:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_binance_ask_bid
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    volumes:
      - exchange_ask_bid:/opt/ask_bid
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket_binance_ask_bid
        syslog-facility: local5

  websocket_okx_market_price:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_market_price
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket_okx_market_price
        syslog-facility: local5

  websocket_okx_positions:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 1 -l INFO -Q websocket_okx_positions
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket_okx_positions
        syslog-facility: local5
