services:
######################## admin
  web:
    image: exchange:latest
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/wait-for-it.sh -q -s -h postgres -p 5432 -- /app/entrypoint.sh
    restart: always
    volumes:
      - exchange_static:/app/static
    networks:
      - layer
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    logging:
      driver: syslog
      options:
        tag: exchange_web
        syslog-facility: local5
######################## rabbitmq
  rabbitmq:
    image: rabbitmq:management
    env_file:
      - .env
    volumes:
      - exchange_rabbitmq:/var/lib/rabbitmq
    ports:
      - "38445:15672"
      - "38692:15692"
    networks:
      - layer
######################## nginx
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - exchange_static:/app/static:ro
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - layer
######################## postgres
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - exchange_postgres:/var/lib/postgresql/data
    networks:
      - layer
######################## redis
  redis:
    image: redis:latest
    entrypoint: redis-server --appendonly yes --maxmemory-policy volatile-ttl --aof-use-rdb-preamble yes --save "" --maxclients 65000
    volumes:
      - exchange_redis:/data
    networks:
      - layer
######################## flower
  flower:
    image: exchange:latest
    entrypoint: celery -A exchange flower -l INFO --host=0.0.0.0 --port=5555
    restart: always
    env_file:
      - .env
    ports:
      - "51455:5555"
    depends_on:
      - rabbitmq
    networks:
      - layer
######################## beat scheduler
  beat:
    image: exchange:latest
    entrypoint: sh -c "sleep 5 && celery -A exchange beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - web
      - rabbitmq
      - redis
      - postgres
      - default
      - position
      - trade
      - emulate
      - websocket
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_scheduler
        syslog-facility: local5
######################## queue default
  default:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 5 -l INFO -Q default
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_default
        syslog-facility: local5
######################## queue position
  position:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 15 -l INFO -Q position
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_position
        syslog-facility: local5
######################## queue trade
  trade:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 10 -l INFO -Q trade
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_trade
        syslog-facility: local5
######################## queue emulate
  emulate:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 10 -l INFO -Q emulate
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_emulate
        syslog-facility: local5
######################## queue websocket
  websocket:
    image: exchange:latest
    entrypoint: celery -A exchange worker -c 2 -l INFO -Q websocket
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - web
    env_file:
      - .env
    networks:
      - layer
    logging:
      driver: syslog
      options:
        tag: exchange_websocket
        syslog-facility: local5

volumes:
  exchange_postgres:
  exchange_redis:
  exchange_static:
  exchange_rabbitmq:

networks:
  layer:
    driver: bridge
