# Generated by Django 5.0.4 on 2024-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='logging',
        ),
        migrations.AlterField(
            model_name='execution',
            name='bill_id',
            field=models.CharField(max_length=255, verbose_name='Bill ID'),
        ),
        migrations.AlterUniqueTogether(
            name='execution',
            unique_together={('bill_id', 'trade_id')},
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
