# Generated by Django 5.0.4 on 2024-06-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0003_execution_binance_okx_bill_id_a59d50_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='mode',
            field=models.CharField(default='trade', max_length=20, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='binance_okx.position'),
        ),
    ]
