# Generated by Django 5.0.4 on 2024-06-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0004_position_mode_alter_execution_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okxcandle',
            name='symbol',
        ),
        migrations.DeleteModel(
            name='BinanceCandle',
        ),
        migrations.DeleteModel(
            name='OkxCandle',
        ),
    ]
