# Generated by Django 5.0.4 on 2024-06-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0005_remove_okxcandle_symbol_delete_binancecandle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('bill_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Bill ID')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='binance_okx.account')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
