# Generated by Django 5.0.4 on 2024-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0006_bill'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(models.F('data__ordId'), name='bill_ord_id_idx'),
        ),
    ]
