# Generated by Django 5.0.4 on 2024-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0007_bill_bill_ord_id_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='search_duration',
            field=models.IntegerField(default=0, help_text='Search duration, seconds', verbose_name='Search duration'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='simultaneous_opening_positions',
            field=models.BooleanField(default=False, verbose_name='Simultaneous opening of positions'),
        ),
    ]
