# Generated by Django 5.0.4 on 2024-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0008_strategy_search_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
