# Generated by Django 5.0.4 on 2024-08-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0010_alter_account_exchange_alter_strategy_first_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='account',
            field=models.ForeignKey(blank=True, help_text='OKX account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='binance_okx.account'),
        ),
        migrations.AddField(
            model_name='position',
            name='trade_ids',
            field=models.JSONField(default=list, verbose_name='Trade IDs'),
        ),
    ]
