# Generated by Django 5.0.4 on 2024-08-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0011_position_account_position_trade_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='target_profit',
            new_name='take_profit',
        ),
    ]
