# Generated by Django 5.0.4 on 2024-10-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0014_symbol_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('order_id', models.CharField(max_length=255, verbose_name='Order ID')),
                ('trade_id', models.CharField(max_length=255, null=True, verbose_name='Trade ID')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='binance_okx.account')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'indexes': [models.Index(models.F('order_id'), name='order_order_id_idx'), models.Index(models.F('trade_id'), name='order_trade_id_idx')],
            },
        ),
    ]
