# Generated by Django 5.0.4 on 2024-10-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0015_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='execution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='execution',
            name='position',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_ord_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_trade_id_idx',
        ),
        migrations.AddField(
            model_name='bill',
            name='mode',
            field=models.CharField(default='trade', max_length=20, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='bill',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='bill',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='binance_okx.symbol'),
        ),
        migrations.AddField(
            model_name='bill',
            name='trade_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Trade ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='binance_okx.symbol'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='binance_okx.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='binance_okx.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Trade ID'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['order_id'], name='bill_order_id_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['trade_id'], name='bill_trade_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='order_order_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trade_id'], name='order_trade_id_idx'),
        ),
        migrations.DeleteModel(
            name='Execution',
        ),
    ]
