# Generated by Django 5.0.4 on 2024-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0016_alter_execution_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuslog',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='bill',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mode'),
        ),
    ]
