# Generated by Django 5.0.4 on 2024-11-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0017_remove_statuslog_created_by_alter_bill_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='created_by',
        ),
    ]
