# Generated by Django 5.0.4 on 2024-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_okx', '0018_remove_account_created_by_remove_strategy_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='reverse',
            field=models.BooleanField(default=False, help_text='Open positions in reverse direction', verbose_name='Reverse'),
        ),
    ]
